/**
 ******************************************************************************
 * @file    wakeword_inference.c
 * @brief   Glue layer: MFCC float32 → INT8 quantisation → ST-AI inference
 *
 * Pipeline
 * ────────
 *  [INMP441 DMA]
 *      │  raw int32 (24-bit left-justified)
 *      ▼
 *  MFCC_IngestBlock()  ──►  MFCC_Compute()
 *      │  g_mfcc_out  float32 (40 × 97)
 *      ▼
 *  WW_Quantise()           float32 → int8 per-tensor affine quantisation
 *      │  s_model_input  int8 (3880 bytes)
 *      ▼
 *  aiRunInference()        ST-AI synchronous forward pass
 *      │  P(wakeword)   float32 ∈ [0, 1]
 *      ▼
 *  WW_RunInference()       threshold → bool decision
 *
 * Quantisation parameters
 * ───────────────────────
 * Read INPUT_SCALE, INPUT_ZP, OUTPUT_SCALE, OUTPUT_ZP from the
 * quantisation report generated by STM32Cube.AI Studio
 * (Model → Analyse → Quantization tab, or network_config.h / network.h).
 *
 * Affine formula (matches TFLite / ST-AI convention):
 *   q = clamp( round(x / input_scale) + input_zp,  -128, 127 )
 *   x = (q - output_zp) * output_scale              ← done inside aiRunInference
 ******************************************************************************
 */

#include "wakeword_inference.h"
#include "mfcc_processing.h"
#include "app_x-cube-ai.h"
#include "norm_stats.h"
#include "main.h"

#include <stdint.h>
#include <stdio.h>
#include <math.h>

/* Paste at the top of the file, after includes */
#define BENCH_N 100U

static uint32_t s_bench_mfcc[BENCH_N];
static uint32_t s_bench_inf[BENCH_N];
static uint32_t s_bench_idx = 0;
static uint8_t  s_bench_done = 0;

void BENCH_Record(uint32_t mfcc_cycles, uint32_t inf_cycles)
{
    if (s_bench_done) return;
    s_bench_mfcc[s_bench_idx] = mfcc_cycles;
    s_bench_inf [s_bench_idx] = inf_cycles;
    if (++s_bench_idx >= BENCH_N)
    {
        s_bench_done = 1;

        /* Compute mean and max */
        uint64_t sum_m = 0, sum_i = 0;
        uint32_t max_m = 0, max_i = 0;
        for (uint32_t k = 0; k < BENCH_N; k++) {
            sum_m += s_bench_mfcc[k]; max_m = s_bench_mfcc[k] > max_m ? s_bench_mfcc[k] : max_m;
            sum_i += s_bench_inf [k]; max_i = s_bench_inf [k] > max_i ? s_bench_inf [k] : max_i;
        }
        float mfcc_mean = (float)(sum_m / BENCH_N) / 280000.0f;
        float inf_mean  = (float)(sum_i / BENCH_N) / 280000.0f;
        float mfcc_max  = (float)max_m / 280000.0f;
        float inf_max   = (float)max_i / 280000.0f;

        printf("\r\n========== BENCHMARK SUMMARY (n=%u) ==========\r\n", BENCH_N);
        printf("  MFCC      : mean=%.2f ms  max=%.2f ms\r\n", mfcc_mean, mfcc_max);
        printf("  Inference : mean=%.2f ms  max=%.2f ms\r\n", inf_mean,  inf_max);
        printf("  Total     : mean=%.2f ms  max=%.2f ms\r\n",
               mfcc_mean + inf_mean, mfcc_max + inf_max);
        printf("  Budget    : 1000 ms  →  headroom=%.0f ms\r\n",
               1000.0f - (mfcc_mean + inf_mean));
        printf("==============================================\r\n\r\n");
    }
}
/* ── Quantisation parameters ─────────────────────────────────────────────
 *
 *  !! READ THESE FROM YOUR CUBE-AI QUANTISATION REPORT !!
 *
 *  In STM32Cube.AI Studio:
 *    Analyse → "Quantization" tab → input tensor row → Scale / Zero-point
 *    Analyse → "Quantization" tab → output tensor row → Scale / Zero-point
 *
 *  They can also be found in the generated network.h / network_config.h:
 *    AI_NETWORK_IN_1_SCALE  /  AI_NETWORK_IN_1_ZEROPOINT
 *    AI_NETWORK_OUT_1_SCALE /  AI_NETWORK_OUT_1_ZEROPOINT
 *
 *  Replace the placeholder values below with your actual values.
 * ──────────────────────────────────────────────────────────────────────── */
#define INPUT_SCALE    STAI_NETWORK_IN_1_SCALE    /* ← replace with your input  scale        */
#define INPUT_ZP       STAI_NETWORK_IN_1_ZERO_POINT       /* ← replace with your input  zero-point   */

#define OUTPUT_SCALE    STAI_NETWORK_OUT_1_SCALE  /* ← replace with your output scale   */
#define OUTPUT_ZP       STAI_NETWORK_OUT_1_ZERO_POINT         /* ← replace with your output zp       */

/* Detection threshold: P(wakeword) must exceed this to trigger.
 * Lowered from 0.85 to 0.70 because:
 *   - Sliding window gives 4 overlapping windows/second → multiple chances
 *   - Cooldown in WW_RunInference prevents false double-triggers
 *   - INMP441 signal path introduces mild distribution shift vs training data
 * If false triggers appear on background speech, raise back toward 0.80.    */
#define WW_THRESHOLD    0.75f

/* ── Internal INT8 input buffer ──────────────────────────────────────────
 *  Sized to hold one full MFCC feature map: 40 coefs × 97 frames = 3880  */
static int8_t s_model_input[MFCC_OUT_SIZE] __attribute__((aligned(32)));

/* ── Helpers ─────────────────────────────────────────────────────────────*/

/**
 * @brief  Clamp an int32 to the signed 8-bit range [-128, 127].
 */
static inline int8_t clamp_i8(int32_t v)
{
    if (v >  127) return  127;
    if (v < -128) return -128;
    return (int8_t)v;
}

/* ── Public API ──────────────────────────────────────────────────────────*/

/**
 * @brief  Quantise g_mfcc_out (float32) into s_model_input (int8).
 *
 *         Uses per-tensor affine quantisation:
 *           q = clamp( round(x / INPUT_SCALE) + INPUT_ZP,  -128, 127 )
 *
 *         Must be called after MFCC_Compute() and before WW_RunInference().
 *         In practice WW_RunInference() calls this internally — you do not
 *         need to call it directly.
 */
void WW_Quantise(void)
{
    const float inv_scale = 1.0f / INPUT_SCALE;

    for (uint32_t frame = 0U; frame < MFCC_NUM_FRAMES; frame++)
    {
        for (uint32_t coef = 0U; coef < MFCC_NUM_COEFS; coef++)
        {
            /* 1 — Read from coef-major source */
            float x = g_mfcc_out[coef * MFCC_NUM_FRAMES + frame];

            /* 2 — Normalise: (x - mean) / std */
            x = (x - mfcc_mean[coef]) / mfcc_std[coef];

            /* 3 — Quantise, write time-major */
            int32_t q = (int32_t)roundf(x * inv_scale) + (int32_t)INPUT_ZP;
            s_model_input[frame * MFCC_NUM_COEFS + coef] = clamp_i8(q);
        }
    }

    /* Clean s_model_input from D-Cache to RAM so ST-AI DMA reads fresh data */
    SCB_CleanDCache_by_Addr(
        (uint32_t *)s_model_input,
        sizeof(s_model_input)
    );

    /* ── CHECKPOINT 5: normalised MFCC value range ───────────────────────
     * g_mfcc_out is COEF-MAJOR: index = coef * NUM_FRAMES + frame
     * so coef = i / NUM_FRAMES  (NOT i % MFCC_NUM_COEFS)                  */
    float x_min =  999.0f, x_max = -999.0f;
    for (uint32_t i = 0U; i < MFCC_OUT_SIZE; i++)
    {
        uint32_t coef = i / MFCC_NUM_FRAMES;   /* correct coef index       */
        if (coef >= MFCC_NUM_COEFS) break;     /* guard against rounding   */
        float xn = (g_mfcc_out[i] - mfcc_mean[coef]) / mfcc_std[coef];
        if (xn < x_min) x_min = xn;
        if (xn > x_max) x_max = xn;
    }
//    printf("[WW]   Normalised MFCC range: min=%.2f  max=%.2f  "
//           "(expect ~[-5, 5])\r\n", x_min, x_max);
//
//    /* ── CHECKPOINT 6: first 5 quantised INT8 values ─────────────────────
//     * Should NOT all be -128 (clamped) or all the same value.              */
//    printf("[WW]   INT8 input[0..4]: %d %d %d %d %d\r\n",
//           s_model_input[0], s_model_input[1],
//           s_model_input[2], s_model_input[3], s_model_input[4]);
}

/**
 * @brief  Quantise MFCCs and run one synchronous inference pass.
 *
 *         Call this from the main loop immediately after MFCC_Compute()
 *         returns (i.e. when g_mfcc_ready was 1).
 *
 * @param  p_wakeword  Output: raw probability P(wakeword) ∈ [0, 1].
 *                     Set to -1.0f if inference failed.
 * @return 1 if wakeword detected (P ≥ WW_THRESHOLD), 0 otherwise.
 */
/* ── Cooldown ─────────────────────────────────────────────────────────────
 * After a detection, suppress further detections for COOLDOWN_MS.
 * Matches COOLDOWN_S = 1.5 s in the Python test script.                   */
#define COOLDOWN_MS   1500U

static uint32_t s_last_detection_tick = 0U;   /* HAL_GetTick() at last detect */

int WW_RunInference(float *p_wakeword)
{
    /* Step 1 — Quantise */
    WW_Quantise();


    /* Step 2 — Inference */
    // In wakeword_inference.c, around WW_RunInference()

    CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
    DWT->CYCCNT = 0;
    DWT->CTRL  |= DWT_CTRL_CYCCNTENA_Msk;

    uint32_t t0 = DWT->CYCCNT;
    float p_ww = aiRunInference(s_model_input,
                                sizeof(s_model_input),
                                OUTPUT_SCALE,
                                OUTPUT_ZP);

    uint32_t t1 = DWT->CYCCNT;

    uint32_t cycles = t1 - t0;
    float    ms     = (float)cycles / 280000.0f;   // 280 MHz
    printf("[BENCH] Inference: %lu cycles  →  %.2f ms\r\n", cycles, ms);
    /* ── CHECKPOINT 7: raw output ────────────────────────────────────────*/
    int raw_ww  = (int)roundf(p_ww  / OUTPUT_SCALE) + (int)OUTPUT_ZP;
    float p_neg = (p_ww >= 0.0f) ? (1.0f - p_ww) : 0.0f;
    printf("[WW]   p_neg=%.4f  p_ww=%.4f  raw_ww_int8=%d  "
           "(expect != -128 when speaking)\r\n",
           p_neg, p_ww, raw_ww);

    if (p_wakeword != NULL)
        *p_wakeword = p_ww;

    if (p_ww < 0.0f)
    {
        printf("[WW]   ERROR: aiRunInference returned -1 (inference failed)\r\n");
        return 0;
    }

    /* Step 3 — Threshold + cooldown */
    uint32_t now        = HAL_GetTick();
    uint32_t elapsed    = now - s_last_detection_tick;
    uint8_t  in_cooldown = (s_last_detection_tick != 0U) &&
                           (elapsed < COOLDOWN_MS);

    int detected = (p_ww >= WW_THRESHOLD) && !in_cooldown;

    if (p_ww >= WW_THRESHOLD && in_cooldown)
        printf("[WW]   (cooldown — %lu ms remaining)\r\n",
               (unsigned long)(COOLDOWN_MS - elapsed));

    if (detected)
    {
        s_last_detection_tick = now;
        printf("[WW]   *** WAKEWORD DETECTED ***  p_ww=%.4f\r\n", p_ww);
    }

    printf("------------------------------------------------------\r\n");

    return detected;
}
