/**
 ******************************************************************************
 * @file    app_x-cube-ai.h
 * @brief   X-CUBE-AI application interface header.
 *
 * This file is generated by STM32Cube.AI during code generation.
 * The definitions below reflect a typical single-network configuration.
 ******************************************************************************
 */

#ifndef APP_X_CUBE_AI_H
#define APP_X_CUBE_AI_H

#ifdef __cplusplus
extern "C" {
#endif

/* ── Includes ──────────────────────────────────────────────────────────────── */
#include "ai_platform.h"

/* ── Public API ────────────────────────────────────────────────────────────── */

/**
 * @brief  Initialize the X-CUBE-AI middleware (called once at startup).
 */
void MX_X_CUBE_AI_Init(void);

/**
 * @brief  Run one inference pass (blocking).
 *         This function is provided for standalone testing; in the wake word
 *         application, inference is driven by wake_word_detection.c directly.
 */
void MX_X_CUBE_AI_Process(void);

#ifdef __cplusplus
}
#endif

#endif /* APP_X_CUBE_AI_H */
