/**
 ******************************************************************************
 * @file    wake_word_detection.h
 * @brief   Wake word inference using the X-CUBE-AI runtime.
 *
 * This module wraps the network generated by STM32Cube.AI (X-CUBE-AI) and
 * provides a simple run-inference API.  The network is trained in Edge
 * Impulse and exported as a C library compatible with X-CUBE-AI.
 *
 * Expected model I/O (adjust if your Edge Impulse model differs):
 *   Input  : 1 × FEATURE_SIZE  float32 (flattened MFCC matrix)
 *   Output : 1 × NUM_CLASSES   float32 (softmax probabilities)
 *
 * Class order must match the order used during Edge Impulse training, e.g.:
 *   [0] background / noise
 *   [1] wake word  ("hey_device", "ok_device", …)
 ******************************************************************************
 */

#ifndef WAKE_WORD_DETECTION_H
#define WAKE_WORD_DETECTION_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include "audio_processing.h"   /* for FEATURE_SIZE */

/* ── Model constants ───────────────────────────────────────────────────────── */

/** Number of output classes – must match your Edge Impulse project. */
#define NUM_CLASSES   2U

/** Index of the wake-word class in the softmax output vector. */
#define WAKEWORD_CLASS_IDX   1U

/* ── Result type ───────────────────────────────────────────────────────────── */

/** Result returned by WakeWordDetection_Run(). */
typedef struct {
    uint8_t  detected;                  /**< 1 if wake word found, else 0  */
    uint8_t  class_idx;                 /**< Index of the top-scored class */
    float    scores[NUM_CLASSES];       /**< Raw softmax scores            */
} WakeWordResult_t;

/* ── Public API ────────────────────────────────────────────────────────────── */

/**
 * @brief  Initialize the X-CUBE-AI network (allocate activations, load weights).
 *         Must be called once before WakeWordDetection_Run().
 * @retval 0   Success.
 * @retval -1  Initialization failed (check UART log for details).
 */
int WakeWordDetection_Init(void);

/**
 * @brief  Run one inference pass on a pre-computed feature vector.
 *
 * @param  features  Pointer to FEATURE_SIZE float32 values (MFCC matrix).
 * @param  result    Pointer to a WakeWordResult_t struct filled by this call.
 * @retval 0   Inference completed (check result->detected).
 * @retval -1  Inference error.
 */
int WakeWordDetection_Run(const float *features, WakeWordResult_t *result);

#ifdef __cplusplus
}
#endif

#endif /* WAKE_WORD_DETECTION_H */
