/**
 ******************************************************************************
 * @file    main.c
 * @brief   Wake word detection main application.
 *
 * Hardware: Nucleo-H743ZI2 + INMP441 I2S microphone
 * Toolchain: STM32CubeIDE + X-CUBE-AI plugin
 *
 * Application flow
 * ────────────────
 *   1. System / peripheral initialization (generated by STM32CubeMX).
 *   2. AudioCapture_Init / Start  → DMA streaming from INMP441 at 16 kHz.
 *   3. WakeWordDetection_Init     → load neural network into SRAM.
 *   4. Main loop:
 *        a. AudioCapture_GetFrame → fills PCM frame buffer.
 *        b. AudioProcessing_ComputeMFCC → MFCC feature matrix.
 *        c. WakeWordDetection_Run → inference.
 *        d. If detected → blink green LED + print UART message.
 *
 * UART debug output is available on the virtual COM port exposed by the
 * ST-LINK USB (USART3 on Nucleo-H743ZI2, 115200 8N1).
 ******************************************************************************
 */

/* USER CODE BEGIN Includes */
#include "main.h"
#include "audio_capture.h"
#include "audio_processing.h"
#include "wake_word_detection.h"
#include <stdio.h>
#include <string.h>
/* USER CODE END Includes */

/* ── Peripheral handles (generated by STM32CubeMX) ─────────────────────────── */
I2S_HandleTypeDef hi2s2;
DMA_HandleTypeDef hdma_spi2_rx;
UART_HandleTypeDef huart3;

/* ── Private function prototypes ───────────────────────────────────────────── */
static void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_DMA_Init(void);
static void MX_I2S2_Init(void);
static void MX_USART3_UART_Init(void);

/* ── Application buffers ───────────────────────────────────────────────────── */

/*
 * PCM sliding-window buffer.
 * Length = (NUM_MFCC_FRAMES - 1) * AUDIO_HOP_SAMPLES + FFT_SIZE
 */
#define PCM_BUF_LEN  ((NUM_MFCC_FRAMES - 1U) * AUDIO_HOP_SAMPLES + FFT_SIZE)
static int16_t pcm_window[PCM_BUF_LEN];

/* MFCC feature buffer. */
static float features[FEATURE_SIZE];

/* Inference result. */
static WakeWordResult_t ww_result;

/* ── Retarget printf to USART3 ─────────────────────────────────────────────── */
#ifdef __GNUC__
int __io_putchar(int ch)
{
    HAL_UART_Transmit(&huart3, (uint8_t *)&ch, 1, HAL_MAX_DELAY);
    return ch;
}
#endif

/* ── main() ────────────────────────────────────────────────────────────────── */

int main(void)
{
    /* ── HAL / clock init ─────────────────────────────────────────────────── */
    HAL_Init();
    SystemClock_Config();   /* 480 MHz, generated by CubeMX              */

    /* ── Peripheral init ──────────────────────────────────────────────────── */
    MX_GPIO_Init();
    MX_DMA_Init();
    MX_I2S2_Init();
    MX_USART3_UART_Init();

    printf("\r\n");
    printf("====================================================\r\n");
    printf("  Wake Word Detection – STM32H743ZI2 + INMP441\r\n");
    printf("====================================================\r\n");

    /* ── Audio capture init ───────────────────────────────────────────────── */
    AudioCapture_Init(&hi2s2);
    AudioProcessing_Init();

    /* ── Neural network init ──────────────────────────────────────────────── */
    if (WakeWordDetection_Init() != 0) {
        printf("[ERR] Network initialization failed – halting.\r\n");
        Error_Handler();
    }

    /* ── Start microphone DMA ─────────────────────────────────────────────── */
    AudioCapture_Start();
    printf("[OK]  Audio capture started at %u Hz\r\n", AUDIO_SAMPLE_RATE_HZ);
    printf("[OK]  Say your wake word...\r\n\r\n");

    /* ── Main loop ────────────────────────────────────────────────────────── */
    while (1) {
        /*
         * 1. Acquire one hop of fresh audio and slide the window.
         *    pcm_window is treated as a circular-shift buffer:
         *    discard the oldest HOP_SAMPLES, append the newest HOP_SAMPLES.
         */
        int16_t hop_buf[AUDIO_HOP_SAMPLES];

        if (AudioCapture_GetHop(hop_buf) != 0) {
            /* Overrun or not started – skip this cycle. */
            continue;
        }

        /* Slide window left by AUDIO_HOP_SAMPLES. */
        memmove(pcm_window,
                pcm_window + AUDIO_HOP_SAMPLES,
                (PCM_BUF_LEN - AUDIO_HOP_SAMPLES) * sizeof(int16_t));

        /* Append new hop at the end. */
        memcpy(pcm_window + PCM_BUF_LEN - AUDIO_HOP_SAMPLES,
               hop_buf,
               AUDIO_HOP_SAMPLES * sizeof(int16_t));

        /*
         * 2. Compute MFCC features from the current window.
         */
        AudioProcessing_ComputeMFCC(pcm_window, features);

        /*
         * 3. Run neural network inference.
         */
        if (WakeWordDetection_Run(features, &ww_result) != 0) {
            printf("[WW] Inference error\r\n");
            continue;
        }

        /*
         * 4. Act on result.
         */
        if (ww_result.detected) {
            printf("[WW] *** WAKE WORD DETECTED ***  "
                   "(score=%.3f)\r\n",
                   (double)ww_result.scores[WAKEWORD_CLASS_IDX]);

            /* Blink green LED for visual feedback. */
            HAL_GPIO_WritePin(LED_GREEN_PORT, LED_GREEN_PIN, GPIO_PIN_SET);
            HAL_Delay(WAKEWORD_LED_DURATION_MS);
            HAL_GPIO_WritePin(LED_GREEN_PORT, LED_GREEN_PIN, GPIO_PIN_RESET);
        }
    }
}

/* ── Peripheral initializers (generated by STM32CubeMX, hand-edited) ────────── */

/**
 * @brief  System clock configuration.
 *         PLL1: HSE 8 MHz → 480 MHz (AHB/APB dividers set for ≤ 240/120/60 MHz).
 *         I2S clock: PLL3 → 49.152 MHz (exact for 16/32/48 kHz audio).
 */
static void SystemClock_Config(void)
{
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

    /* Supply configuration: LDO, VOS0 for 480 MHz. */
    HAL_PWREx_ConfigSupply(PWR_LDO_SUPPLY);
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE0);
    while (!__HAL_PWR_GET_FLAG(PWR_FLAG_VOSRDY)) {}

    /* Enable HSE oscillator. */
    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
    RCC_OscInitStruct.HSEState       = RCC_HSE_BYPASS;
    RCC_OscInitStruct.PLL.PLLState   = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource  = RCC_PLLSOURCE_HSE;
    /* PLL1: 8 MHz HSE, DIVM=2 → 4 MHz, DIVN=240 → 960 MHz VCO, DIVP=2 → 480 MHz */
    RCC_OscInitStruct.PLL.PLLM       = 2;
    RCC_OscInitStruct.PLL.PLLN       = 240;
    RCC_OscInitStruct.PLL.PLLP       = 2;
    RCC_OscInitStruct.PLL.PLLQ       = 4;
    RCC_OscInitStruct.PLL.PLLR       = 2;
    RCC_OscInitStruct.PLL.PLLRGE     = RCC_PLL1VCIRANGE_2;
    RCC_OscInitStruct.PLL.PLLVCOSEL  = RCC_PLL1VCOWIDE;
    RCC_OscInitStruct.PLL.PLLFRACN   = 0;
    HAL_RCC_OscConfig(&RCC_OscInitStruct);

    /* System clock from PLL1. */
    RCC_ClkInitStruct.ClockType      = RCC_CLOCKTYPE_HCLK  | RCC_CLOCKTYPE_SYSCLK
                                     | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2
                                     | RCC_CLOCKTYPE_D3PCLK1 | RCC_CLOCKTYPE_D1PCLK1;
    RCC_ClkInitStruct.SYSCLKSource   = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.SYSCLKDivider  = RCC_SYSCLK_DIV1;   /* 480 MHz */
    RCC_ClkInitStruct.AHBCLKDivider  = RCC_HCLK_DIV2;     /* 240 MHz */
    RCC_ClkInitStruct.APB3CLKDivider = RCC_APB3_DIV2;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_APB1_DIV2;
    RCC_ClkInitStruct.APB2CLKDivider = RCC_APB2_DIV2;
    RCC_ClkInitStruct.APB4CLKDivider = RCC_APB4_DIV2;
    HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_4);
}

/**
 * @brief  GPIO initialization.
 *         LD1 (green) PB0, LD3 (red) PB14 as push-pull outputs.
 *         B1 (user button) PC13 as input with pull-up.
 */
static void MX_GPIO_Init(void)
{
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    __HAL_RCC_GPIOB_CLK_ENABLE();
    __HAL_RCC_GPIOC_CLK_ENABLE();

    /* LEDs – default off. */
    HAL_GPIO_WritePin(LED_GREEN_PORT, LED_GREEN_PIN, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(LED_RED_PORT,   LED_RED_PIN,   GPIO_PIN_RESET);

    GPIO_InitStruct.Pin   = LED_GREEN_PIN | LED_RED_PIN;
    GPIO_InitStruct.Mode  = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull  = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(LED_GREEN_PORT, &GPIO_InitStruct);

    /* User button. */
    GPIO_InitStruct.Pin  = USER_BUTTON_PIN;
    GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
    GPIO_InitStruct.Pull = GPIO_PULLUP;
    HAL_GPIO_Init(USER_BUTTON_PORT, &GPIO_InitStruct);
}

/**
 * @brief  DMA controller initialization.
 *         DMA1 stream0 is used for I2S2 RX (peripheral→memory, circular).
 */
static void MX_DMA_Init(void)
{
    __HAL_RCC_DMA1_CLK_ENABLE();

    hdma_spi2_rx.Instance                 = DMA1_Stream0;
    hdma_spi2_rx.Init.Request             = DMA_REQUEST_SPI2_RX;
    hdma_spi2_rx.Init.Direction           = DMA_PERIPH_TO_MEMORY;
    hdma_spi2_rx.Init.PeriphInc           = DMA_PINC_DISABLE;
    hdma_spi2_rx.Init.MemInc              = DMA_MINC_ENABLE;
    hdma_spi2_rx.Init.PeriphDataAlignment = DMA_PDATAALIGN_HALFWORD;
    hdma_spi2_rx.Init.MemDataAlignment    = DMA_MDATAALIGN_HALFWORD;
    hdma_spi2_rx.Init.Mode                = DMA_CIRCULAR;
    hdma_spi2_rx.Init.Priority            = DMA_PRIORITY_HIGH;
    hdma_spi2_rx.Init.FIFOMode            = DMA_FIFOMODE_DISABLE;
    HAL_DMA_Init(&hdma_spi2_rx);

    __HAL_LINKDMA(&hi2s2, hdmarx, hdma_spi2_rx);

    HAL_NVIC_SetPriority(DMA1_Stream0_IRQn, 0, 0);
    HAL_NVIC_EnableIRQ(DMA1_Stream0_IRQn);
}

/**
 * @brief  I2S2 initialization for INMP441.
 *
 *         Mode     : Master receive, I2S Philips standard
 *         Data bits: 24-bit in 32-bit frame (DATALEN=24, CHLEN=32)
 *         MCLK     : disabled
 *         Clock    : derived from PLL3 (49.152 MHz) for exact 16 kHz
 *
 *         PLL3 configuration (set in SystemClock_Config or CubeMX):
 *           DIVM3=4, DIVN3=96, DIVP3=3 → 49.152 MHz
 *         I2S prescaler: DIV=24 → I2SCLK = 49.152 / (2×24) = 1.024 MHz
 *         BCK  = 1.024 MHz / (32 bits × 2 channels) = 16 000 Hz ✓
 */
static void MX_I2S2_Init(void)
{
    __HAL_RCC_SPI2_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();

    /*
     * Configure I2S2 GPIO pins:
     *   PB12 – I2S2_WS   (AF5)
     *   PB13 – I2S2_CK   (AF5)
     *   PB15 – I2S2_SDI  (AF5)
     */
    GPIO_InitTypeDef GPIO_InitStruct = {0};
    GPIO_InitStruct.Pin       = GPIO_PIN_12 | GPIO_PIN_13 | GPIO_PIN_15;
    GPIO_InitStruct.Mode      = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull      = GPIO_NOPULL;
    GPIO_InitStruct.Speed     = GPIO_SPEED_FREQ_MEDIUM;
    GPIO_InitStruct.Alternate = GPIO_AF5_SPI2;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

    hi2s2.Instance          = SPI2;
    hi2s2.Init.Mode         = I2S_MODE_MASTER_RX;
    hi2s2.Init.Standard     = I2S_STANDARD_PHILIPS;
    hi2s2.Init.DataFormat   = I2S_DATAFORMAT_24B;
    hi2s2.Init.MCLKOutput   = I2S_MCLKOUTPUT_DISABLE;
    hi2s2.Init.AudioFreq    = I2S_AUDIOFREQ_16K;
    hi2s2.Init.CPOL         = I2S_CPOL_LOW;
    hi2s2.Init.FirstBit     = I2S_FIRSTBIT_MSB;
    hi2s2.Init.WSInversion  = I2S_WS_INVERSION_DISABLE;
    hi2s2.Init.IOSwap       = I2S_IO_SWAP_DISABLE;
    hi2s2.Init.Data24BitAlignment = I2S_DATA_24BIT_ALIGNMENT_RIGHT;
    hi2s2.Init.FifoThreshold      = I2S_FIFO_THRESHOLD_01DATA;
    hi2s2.Init.MasterKeepIOState  = I2S_MASTER_KEEP_IO_STATE_DISABLE;
    hi2s2.Init.SlaveExtendedMode  = I2S_SLAVE_EXTEND_DISABLE;
    HAL_I2S_Init(&hi2s2);
}

/**
 * @brief  USART3 initialization (virtual COM port via ST-LINK, 115200 8N1).
 */
static void MX_USART3_UART_Init(void)
{
    __HAL_RCC_USART3_CLK_ENABLE();
    __HAL_RCC_GPIOD_CLK_ENABLE();

    GPIO_InitTypeDef GPIO_InitStruct = {0};
    /* PD8 – USART3_TX, PD9 – USART3_RX */
    GPIO_InitStruct.Pin       = GPIO_PIN_8 | GPIO_PIN_9;
    GPIO_InitStruct.Mode      = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull      = GPIO_NOPULL;
    GPIO_InitStruct.Speed     = GPIO_SPEED_FREQ_LOW;
    GPIO_InitStruct.Alternate = GPIO_AF7_USART3;
    HAL_GPIO_Init(GPIOD, &GPIO_InitStruct);

    huart3.Instance          = USART3;
    huart3.Init.BaudRate     = 115200;
    huart3.Init.WordLength   = UART_WORDLENGTH_8B;
    huart3.Init.StopBits     = UART_STOPBITS_1;
    huart3.Init.Parity       = UART_PARITY_NONE;
    huart3.Init.Mode         = UART_MODE_TX_RX;
    huart3.Init.HwFlowCtl    = UART_HWCONTROL_NONE;
    huart3.Init.OverSampling = UART_OVERSAMPLING_16;
    HAL_UART_Init(&huart3);
}

/* ── ISR stubs for DMA (required by HAL) ───────────────────────────────────── */

/**
 * @brief  DMA1 Stream0 interrupt handler.
 */
void DMA1_Stream0_IRQHandler(void)
{
    HAL_DMA_IRQHandler(&hdma_spi2_rx);
}

/* ── Error handler ─────────────────────────────────────────────────────────── */

void Error_Handler(void)
{
    __disable_irq();
    /* Turn on red LED to signal fault. */
    HAL_GPIO_WritePin(LED_RED_PORT, LED_RED_PIN, GPIO_PIN_SET);
    while (1) {}
}

#ifdef USE_FULL_ASSERT
void assert_failed(uint8_t *file, uint32_t line)
{
    printf("[ASSERT] %s:%lu\r\n", file, line);
}
#endif
