/**
 ******************************************************************************
 * @file    wake_word_detection.c
 * @brief   Wake word inference using the X-CUBE-AI runtime.
 *
 * The network files (network.h / network_data.h / network.c / network_data.c)
 * are generated by STM32Cube.AI from your trained Edge Impulse model.
 * See X-CUBE-AI/App/app_x-cube-ai.c for the generation workflow.
 ******************************************************************************
 */

#include "wake_word_detection.h"
#include "main.h"

/*
 * X-CUBE-AI generated headers.
 * These are produced when you import the .tflite/.onnx model into
 * STM32Cube.AI and generate code.
 *
 * The include paths are set up in the STM32CubeIDE project settings.
 */
#include "network.h"
#include "network_data.h"

#include <string.h>
#include <stdio.h>

/* ── Private state ─────────────────────────────────────────────────────────── */

/** Network handle (allocated statically). */
static ai_handle network = AI_HANDLE_NULL;

/**
 * Activation buffer for the network.
 * The required size is reported by STM32Cube.AI during code generation
 * (shown in the analysis report as "activations size").
 * The macro AI_NETWORK_DATA_ACTIVATIONS_SIZE is defined in network_data.h.
 */
AI_ALIGNED(4)
static ai_u8 activations[AI_NETWORK_DATA_ACTIVATIONS_SIZE];

/** Input / output tensor descriptors. */
static ai_buffer input_data[AI_NETWORK_IN_NUM];
static ai_buffer output_data[AI_NETWORK_OUT_NUM];

/* ── Public API ────────────────────────────────────────────────────────────── */

int WakeWordDetection_Init(void)
{
    ai_error err;

    /* Create network instance. */
    const ai_network_params params = {
        AI_NETWORK_DATA_WEIGHTS(ai_network_data_weights_get()),
        AI_NETWORK_DATA_ACTIVATIONS(activations)
    };

    err = ai_network_create(&network, AI_NETWORK_DATA_CONFIG);
    if (err.type != AI_ERROR_NONE) {
        printf("[WW] ai_network_create error %d/%d\r\n",
               err.type, err.code);
        return -1;
    }

    if (!ai_network_init(network, &params)) {
        err = ai_network_get_error(network);
        printf("[WW] ai_network_init error %d/%d\r\n",
               err.type, err.code);
        return -1;
    }

    /* Retrieve the actual I/O buffer descriptors from the network. */
    ai_network_inputs_get(network, input_data);
    ai_network_outputs_get(network, output_data);

    printf("[WW] Network initialized OK. In: %u floats, Out: %u classes\r\n",
           (unsigned)AI_NETWORK_IN_1_SIZE, (unsigned)NUM_CLASSES);
    return 0;
}

int WakeWordDetection_Run(const float *features, WakeWordResult_t *result)
{
    if (network == AI_HANDLE_NULL || result == NULL) {
        return -1;
    }

    /* Point input buffer at the feature vector. */
    input_data[0].data = AI_HANDLE_PTR((void *)features);

    /* Allocate a local output buffer and point the output descriptor at it. */
    float out_buf[NUM_CLASSES];
    output_data[0].data = AI_HANDLE_PTR(out_buf);

    /* Run inference. */
    ai_i32 n_batch = ai_network_run(network, input_data, output_data);
    if (n_batch != 1) {
        ai_error err = ai_network_get_error(network);
        printf("[WW] ai_network_run error %d/%d\r\n",
               err.type, err.code);
        return -1;
    }

    /* Parse results. */
    memcpy(result->scores, out_buf, sizeof(result->scores));

    /* Find the class with the highest score. */
    result->class_idx = 0;
    for (uint8_t i = 1; i < NUM_CLASSES; i++) {
        if (result->scores[i] > result->scores[result->class_idx]) {
            result->class_idx = i;
        }
    }

    /*
     * Threshold check: treat as detected only when the wake-word class
     * probability exceeds WAKEWORD_THRESHOLD (scaled to [0,1]).
     */
    float threshold = (float)WAKEWORD_THRESHOLD / 255.0f;
    result->detected = (result->class_idx == WAKEWORD_CLASS_IDX)
                       && (result->scores[WAKEWORD_CLASS_IDX] >= threshold)
                       ? 1U : 0U;

    return 0;
}
